### ISSUE TITLE
File Not Found?

### ISSUE THREAD

**Issue by BimoSora** [XMYSTERlOUSX/mega-link-downloader-bot#12]
![Screenshot_20211203-024114_Firefox](https://user-images.githubusercontent.com/16408431/144491763-cc741c0f-2da5-4e06-8795-c341bdb1de5d.jpg)

**Comment by XMYSTERlOUSX** [comment]
Thank you for sharing the error by opening an issue. Sorry for that it was a typo! [Fixed it.](https://github.com/XMYSTERlOUSX/mega-link-downloader-bot/commit/ccdf27a5f5767e43f77b6a5bef3777f174d63370). Kindly make sure to redeploy.
