### ISSUE TITLE
can't upload 1.95gb file directly and instead it's separate and doesn't support chinese language files

### ISSUE THREAD

**Issue by BimoSora** [XMYSTERlOUSX/mega-link-downloader-bot#13]
can't upload 1.95gb file directly and instead it's separate and doesn't support chinese language files
![Screenshot_20211217-195331_Telegraph](https://user-images.githubusercontent.com/16408431/146547641-b3bf57d9-7672-4c2c-9d68-a8661d6c4aa4.jpg)

**Comment by XMYSTERlOUSX** [comment]
> can't upload 1.95gb file directly and instead it's separate and doesn't support chinese language files ![Screenshot_20211217-195331_Telegraph](https://user-images.githubusercontent.com/16408431/146547641-b3bf57d9-7672-4c2c-9d68-a8661d6c4aa4.jpg)

File size is a telegram server side limitation! I can't quite understand what do you mean by `doesn't support chinese language files`
