### ISSUE TITLE
Redis pass and id

### ISSUE THREAD

**Issue by pavneetsingh-00** [XMYSTERlOUSX/mega-link-downloader-bot#2]
I am not able to find redis values

**Comment by XMYSTERlOUSX** [comment]
Ok I will Provide a detailed guide of how to obtain them soon.

**Comment by XMYSTERlOUSX** [comment]
> I am not able to find redis values

Sorry forgot you here. I have completely updated the repo and I have provided a complete video tutorial on how to obtain Redis details here :- https://t.me/botzupdate/5
