### ISSUE TITLE
Add support for google team drive upload

### ISSUE THREAD

**Issue by askfriends** [XMYSTERlOUSX/mega-link-downloader-bot#4]
It would be nice if you implement google tead drive aka shared drive support, so that files/folders are cloned from mega to gdrive.

**Comment by XMYSTERlOUSX** [comment]
> It would be nice if you implement google tead drive aka shared drive support, so that files/folders are cloned from mega to gdrive.

Nope! The goal was to upload mega files through telegram! You can get mega files to shared drive with mirror bots always! (Eg :- Slam Mirror / Tor-Toolkit)
