### ISSUE TITLE
Why It's Not Supporting Folder ?

### ISSUE THREAD

**Issue by flaskvol** [XMYSTERlOUSX/mega-link-downloader-bot#9]
It's Not Supporting Folder Link Of Mega !

**Comment by XMYSTERlOUSX** [comment]
> It's Not Supporting Folder Link Of Mega !

Yeah! I have clearly stated that in the readme that folder support is **not yet implemented!**

**Comment by BimoSora** [comment]
> > It's Not Supporting Folder Link Of Mega !
> 
> Yeah! I have clearly stated that in the readme that folder support is **not yet implemented!**

I need it urgently because there are some mega videos in the folder
